version: '3.4'
services:
  postgres-service:
    container_name: postgres-service
    hostname: postgres-service
    image: postgres:10.8
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: phil.poc.ia
      POSTGRES_DB: poc_db
      TZ: GMT-3
    ports: 
      - "20000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    hostname: rabbitmq-service
    environment:
      RABBITMQ_ERLANG_COOKIE: erlang.SECRET.cookie
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: phil.poc.ia
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
     - "17000:15672"
  web:
    container_name: web
    hostname: web
    build: 
      context: ./web
      dockerfile: Dockerfile-deploy
    tty: true
    ports:
      - "16000:5000"
    volumes:
      - './web:/home/web'
    entrypoint:
      - entrypoint.sh
  ml-service:
    container_name: ml-service
    hostname: ml-service
    build: 
      context: ./ml-service
      dockerfile: Dockerfile-deploy
    tty: true
    volumes:
      - './ml-service:/home/service'
    entrypoint:
      - entrypoint.sh
    
volumes:
  web:
  ml-service:
  db-data:

